{
  imports = [
    ./alpha.nix
    ./auto-save.nix
    ./bufferline.nix
    ./claudecode.nix
    ./cmp.nix
    ./copilot-vim.nix
    ./csvview.nix
    ./dressing.nix
    ./flash.nix
    ./gitsigns.nix
    ./image.nix
    ./indent-blankline.nix
    ./lazygit.nix
    ./lsp-signature.nix
    ./lsp.nix
    ./lualine.nix
    ./lz-n.nix
    ./noice.nix
    ./nvim-surround.nix
    ./nvim-tree.nix
    ./obsidian.nix
    ./render-markdown.nix
    ./skkeleton.nix
    ./telescope.nix
    ./todo-comments.nix
    ./treesitter.nix
    ./treesitter-context.nix
    ./trouble.nix
    ./wakatime.nix
    ./web-devicons.nix
    ./which-key.nix
    ./yazi.nix
  ];
}
